// Shared copy for all pages (LV + EN).

export const COPY = {
  lv: {
    nav: { about: 'Par mums', services: 'Pakalpojumi', gallery: 'Galerija', shows: 'Koncerti', contact: 'Sazināties' },
    cta: 'Rezervēt vakaru',
    ctaShort: 'Rezervēt',
    book: 'Pieprasīt cenu',
    listen: 'Klausīties',
    tagline: 'Dzīvā mūzika jūsu vakaram',
    heroSub: 'Pieci mūziķi no Liepājas. Vakars, ko atcerēsies.',
    yearsTogether: 'Liepāja',
    aboutLead: 'Mēs spēlējam to, ko gribi dzirdēt. Un to, ko vēl nezini, ka gribi.',
    aboutBody: 'Plāns B ir piecu cilvēku sastāvs no Liepājas. Klasika, mūsdienu hīti, latviešu zelta fonds, drīzumā arī oriģinālmūzika. Vakara repertuāru lasām pēc telpas.',
    eventsTitle: 'Kur mēs spēlējam',
    eventsSub: 'No klusas viesistabas līdz pilnai zālei.',
    events: [
      { title: 'Kāzas', body: 'No pirmā deju soļa līdz pēdējam tostam.' },
      { title: 'Korporatīvi', body: 'Gada balles, atklāšanas, prezentācijas.' },
      { title: 'Privatas ballītes', body: 'Jubilejas, kāzu jubilejas, slēgti pasākumi.' },
      { title: 'Festivāli', body: 'Brīvdabas skatuves un pilsētas svētki.' },
    ],
    galleryTitle: 'No skatuves',
    galleryCaption: 'Vakars mēģinājumu telpā · 2026',
    showsTitle: 'Tuvākie koncerti',
    showsSub: 'Atvērti pasākumi — visi laipni gaidīti.',
    shows: [
      { date: '14.06', city: 'Rīga', venue: 'Hanzas Perons', tag: 'Vasaras atklāšana' },
      { date: '28.06', city: 'Cēsis', venue: 'Pils parks', tag: 'Brīvdabas koncerts' },
      { date: '12.07', city: 'Liepāja', venue: 'Lielais dzintars', tag: 'Jūras festivāls' },
      { date: '02.08', city: 'Sigulda', venue: 'Siguldas estrāde', tag: 'Augusta vakari' },
    ],
    quoteWedding: '“Visu vakaru deju grīda nebija tukša ne minūti. Pat vecmāmiņa dejoja.”',
    quoteWeddingBy: '— Anna & Mārtiņš, kāzas Cēsīs',
    quoteCorp: '“Profesionāli, punktuāli, un viesi joprojām runā par to vakaru.”',
    quoteCorpBy: '— SEB Baltika, gada balle',
    contactTitle: 'Pastāstiet par savu vakaru',
    contactSub: 'Atbildam 24 stundu laikā.',
    fields: { name: 'Vārds', email: 'E-pasts', phone: 'Telefons', date: 'Datums', venue: 'Norises vieta', type: 'Pasākuma veids', message: 'Pastāstiet vairāk' },
    submit: 'Nosūtīt pieprasījumu',
    footer: 'Plāns B · Liepāja · ',
    listenOn: 'Klausies',
    setlistLabel: 'Repertuārs',
    setlist: 'No Raimonda Paula līdz Daft Punk. Latviešu, krievu, angļu — pēc vakara noskaņas.',
    aboutFigures: [
      { n: '5', l: 'mūziķi' },
      { n: 'Liepāja', l: 'mājas pilsēta' },
      { n: '180+', l: 'pasākumi' },
    ],
    scrollHint: 'Ritiniet',
    privacyLink: 'Privātuma paziņojums',
  },
  en: {
    nav: { about: 'About', services: 'Services', gallery: 'Gallery', shows: 'Shows', contact: 'Contact' },
    cta: 'Book the night',
    ctaShort: 'Book now',
    book: 'Request a quote',
    listen: 'Listen',
    tagline: 'Live music for the night you remember',
    heroSub: 'Five musicians from Liepāja. A night you remember.',
    yearsTogether: 'Liepāja',
    aboutLead: 'We play what you want to hear. And what you didn\'t know you wanted.',
    aboutBody: 'Plāns B is a five-piece from Liepāja. Standards, modern hits, Latvian classics, and originals on the way. We read the room.',
    eventsTitle: 'Where we play',
    eventsSub: 'From a quiet living room to a full hall.',
    events: [
      { title: 'Weddings', body: 'From first dance to last toast.' },
      { title: 'Corporate', body: 'Year-end parties, openings, launches.' },
      { title: 'Private parties', body: 'Birthdays, anniversaries, closed events.' },
      { title: 'Festivals', body: 'Open-air stages and city celebrations.' },
    ],
    galleryTitle: 'From the stage',
    galleryCaption: 'A night in the rehearsal room · 2026',
    showsTitle: 'Upcoming shows',
    showsSub: 'Open events — everyone welcome.',
    shows: [
      { date: 'Jun 14', city: 'Riga',    venue: 'Hanzas Perons',     tag: 'Summer opener' },
      { date: 'Jun 28', city: 'Cēsis',   venue: 'Castle park',       tag: 'Open air' },
      { date: 'Jul 12', city: 'Liepāja', venue: 'Great Amber',       tag: 'Sea festival' },
      { date: 'Aug 02', city: 'Sigulda', venue: 'Sigulda bandshell', tag: 'August nights' },
    ],
    quoteWedding: '“The dance floor was never empty. Even grandma was dancing.”',
    quoteWeddingBy: '— Anna & Mārtiņš, wedding in Cēsis',
    quoteCorp: '“Professional, on time, and our guests are still talking about it.”',
    quoteCorpBy: '— SEB Baltic, annual gala',
    contactTitle: 'Tell us about your night',
    contactSub: 'We reply within 24 hours.',
    fields: { name: 'Name', email: 'Email', phone: 'Phone', date: 'Date', venue: 'Venue', type: 'Event type', message: 'Tell us more' },
    submit: 'Send request',
    footer: 'Plāns B · Liepāja · ',
    listenOn: 'Listen',
    setlistLabel: 'Setlist',
    setlist: 'Raimonds Pauls to Daft Punk. Latvian, Russian, English — read by the room.',
    aboutFigures: [
      { n: '5', l: 'musicians' },
      { n: 'Liepāja', l: 'home town' },
      { n: '180+', l: 'shows played' },
    ],
    scrollHint: 'Scroll',
    privacyLink: 'Privacy notice',
  },
};
